### PR TITLE
Improve/Push Data in Redis

### PR DESCRIPTION
**Pull request by geleazar1000111**
AC 9/3/2020-9/17/2020
- Per discussion w/ the frontend team, improve the way we are getting info on specific candidates
- We also want to add more real data to Redis to be used by the frontend -> add code for populating other endpoints in csv2redis

### CODE REVIEW

**Comment by geleazar1000111** [comment]
added the redis script i used to populate my local redis database. steps should be simple:
1. Make sure RedisJSON module is loaded and server is running
2. Switch to redis_data folder and call `python3 scraper_to_redis.py`
you can then test and see the data through the api (only candidates and specific candidates though, other endpoints still wip)

**Review by rwalek668 — APPROVED** [review]
Looks good! My one suggestion would be that totalContributions should only factor in RCPT type & LOAN type entries in the spreadsheet (column rec_type) otherwise we will be double counting data.  I think the code is good to submit though, and we can fix this after.  (https://github.com/codeforsanjose/open-disclosure/blob/master/data_pipeline/data_processing/aggregatedcsv2redis.py has some additional context on how to work with this column)

**Comment by geleazar1000111** [comment]
Gotcha, I'll merge it for now and make the changes later. I'm wondering what we do for the expense types that are not RCPT or LOAN- do we simply say TotalContributions is 0? Do those entities also count as committees and if not, can we exclude them?

**Comment by rwalek668** [comment]
Yes that's correct.  For expense types that are not RCPT or LOAN, we will still want to track these (eventually) as separate fields under Committee/Candidate in the API's, but its misleading to include them in total contribution as the same money can get donated (RCPT) and then spent (EXPN) leading to us double counting it.

**Pull request merged**
