### PR TITLE
Push data to redis server

### PR DESCRIPTION
**Pull request by geleazar1000111**
https://docs.google.com/drawings/d/1s9YGnXIOuPWiQJZQmZqBTnJFUlhGSC04DN68TD-ZIkg/edit
As described in the flowchart above, the data api is to push data in the correct shape to the Redis server which the frontend can query. An intermediary API between the Redis server and the UI may be needed if there's no way for the UI to directly connect to Redis.

### CODE REVIEW

**Comment by geleazar1000111** [comment]
The data API has been split into two modules: one is within data pipeline and pushes data to Redis, while this one (redis-api) will serve the data from Redis to the frontend. data_api will be deleted in the future. Ok to delete in this pr or should I wait until after the demo?

**Comment by geleazar1000111** [comment]
I also have some code that will populate Redis with Candidate data which I can add to @cmatthey's python file

**Comment by JMStudiosJoe** [comment]
Is this pr ready for review and merging?

**Comment by geleazar1000111** [comment]
@JMStudiosJoe yeah, I wanted @rwalek668 to take a look at it, but I think it should be fine to merge

**Review by rwalek668 — APPROVED** [review]
Code looks good to merge! 

One idea for future improvement: your "readme" is GREAT! It could be linked/integrated with the Open Disclosure top-level readme.

I think perhaps the next step will be to set up a redis server in AWS, and try loading some data.

**Pull request merged**
