### PR TITLE
Add current and correct metadata

### PR DESCRIPTION
**Pull request by geleazar1000111**
Added metadata population method and serve real metadata from routes

### CODE REVIEW

**Comment by ychoy** [comment]
@geleazar1000111  this is what I see when I query for `DateProcessed` in GraphiQL. Are you seeing something different? 

```
{
  "data": {
    "metadata": {
      "DateProcessed": "2020-07-20"
    },
    "allMetadata": {
      "nodes": [
        {
          "DateProcessed": "2020-07-20"
        }
      ]
    }
  },
  "extensions": {}
}
```

**Comment by geleazar1000111** [comment]
@ychoy when i access the /metadata endpoint by running the api locally, i get
`{"DateProcessed":"2020-10-22 20:55:10.813291"}`
maybe the redis population script needs to be run again in order to update it? let me take a look

**Comment by geleazar1000111** [comment]
ok yeah, so running gatsby i get July but when accessing the api by itself i get the correct date. Apparently the local gatsby server is accessing data from the deployed api. I replaced ${HOSTNAME} with localhost:5000 in `gatsby-node.js` and got:
```
{
  "data": {
    "allMetadata": {
      "edges": [
        {
          "node": {
            "DateProcessed": "2020-10-22 20:55:10.813291"
          }
        }
      ]
    },
    "metadata": {
      "DateProcessed": "2020-10-22 20:55:10.813291"
    }
  },
  "extensions": {}
}
```

**Review by ychoy — APPROVED** [review]

**Comment by ychoy** [comment]
Awesome, thanks! @geleazar1000111 will you be able to redeploy both API and frontend after this gets merged or do we need to ping @darpham?

**Comment by geleazar1000111** [comment]
@ychoy we probably have to ping @darpham, I don't have access to the AWS credentials

**Pull request merged**
