### PR TITLE
Update API

### PR DESCRIPTION
**Pull request by geleazar1000111**
Updated the API to include:

- OfficeElection.TotalFunding currently includes only RCPT, needs to include RCPT + LOAN
8:44
- Candidate.FundingByGeo and Candidate.FundingByType both only include RCPT, need to include RCPT + LOAN
8:44
- We want to add the fields that are currently in the candidate JSON files (website, etc.) to the API so we no longer have to join on candidate ID
8:45
- We want to add real data for measures (G and H instead of X, Y and Z) and add fields from the client JSON files to the API (name, description, ballotLanguage?)

### CODE REVIEW

**Comment by ejanzer** [comment]
Thanks for making these changes! I think I'll let someone more familiar with the backend code review it :)

**Review by alessandro-pianetta — APPROVED** [review]

**Comment by ejanzer** [comment]
Hey @geleazar1000111, is there anything I need to do to get these changes locally so I can test them? I tried re-running aggregatedcsv2redis.py and restarting flask, but the data looks the same as before.

**Comment by geleazar1000111** [comment]
@ejanzer Hmm I don't think so, your redis server is running too right?

**Comment by ejanzer** [comment]
@geleazar1000111 Yeah my redis server is running. Do I need to restart it or anything?

**Pull request merged**
